-- INSERT INTO cities (id, name) VALUES (1000,'Казань');
-- INSERT INTO cities (id, name) VALUES (2000,'Москва');
-- INSERT INTO cities (id, name) VALUES (3000,'Санкт-Петербург');
-- INSERT INTO cities (id, name) VALUES (4000,'Йошкар-Ола');
--
-- INSERT  INTO sports_clubs (id, name, city_id) VALUES (1000, 'MAXIMUS', 1);
-- INSERT  INTO sports_clubs (id, name, city_id) VALUES (2000,'DYNAMITE GYM', 2 );
-- INSERT  INTO sports_clubs (id, name, city_id) VALUES (3000,'Brilliant GYM', 3 );
-- INSERT  INTO sports_clubs (id, name, city_id) VALUES (4000,'Alex Fitness', 1 );
-- INSERT  INTO sports_clubs (id, name, city_id) VALUES (5000,'Powerhouse GYM', 3 );
-- INSERT  INTO sports_clubs (id, name, city_id) VALUES (6000,'Академия Тенниса', 1 );
--
-- INSERT INTO sections (id, name) VALUES (1000, 'Воллейбол');
-- INSERT INTO sections (id, name) VALUES (2000, 'Бокс');
-- INSERT INTO sections (id, name) VALUES (3000, 'Аквааэробика');
-- INSERT INTO sections (id, name) VALUES (4000, 'Настольный теннис');
-- INSERT INTO sections (id, name) VALUES (5000, 'Фитнесс');
-- INSERT INTO sections (id, name) VALUES (6000, 'Танцы живота');
-- INSERT INTO sections (id, name) VALUES (7000, 'Тяжелая атлетика');
--
-- INSERT INTO teachers (id, age, full_name, phone_number, regalia, work_experience, section_id, sports_club_id)
--     VALUES (1000, 27, 'Алексеев Антон', '+78432734636', 'Чемпион республики Корелия по боксу', 4, 2, 3);
--
-- INSERT INTO trainings (id, day, time, teacher_id) VALUES  (1000, 2, '12:00', 1);
-- INSERT INTO trainings (id, day, time, teacher_id) VALUES  (2000, 2, '12:00', 1);
-- INSERT INTO trainings (id, day, time, teacher_id) VALUES  (3000, 4, '14:00', 1);
-- INSERT INTO trainings (id, day, time, teacher_id) VALUES  (4000, 2, '16:00', 1);
-- INSERT INTO trainings (id, day, time, teacher_id) VALUES  (5000, 3, '10:00', 1);
-- INSERT INTO trainings (id, day, time, teacher_id) VALUES  (6000, 5, '18:00', 1);
-- INSERT INTO trainings (id, day, time, teacher_id) VALUES  (7000, 1, '14:00', 1);
--
INSERT INTO users (id, login, password, role) VALUES (1, 'vasya', '123','ROLE_USER');
INSERT INTO users (id, login, password, role) VALUES (2, 'admin', 'admin', 'ROLE_ADMIN');